#pragma once

#include "../../Config/config_mqtt.h"

#define MQTTDEVICE_USE_GLOBAL_CONFIG			true
#define MQTTDEVICE_INITIALLY_ENABLED			true
#define MQTTDEVICE_IMPORTANT					true

#define TOPIC_BASE_MQTT_DEVICE					"/devices"
#define TOPIC_BASE_MQTT_DEVICE_AVAILABILITY		TOPIC_BASE_AVAILABILITY	
#define TOPIC_BASE_MQTT_DEVICE_JSON_COMMAND		TOPIC_BASE_JSON_COMMAND								
#define TOPIC_BASE_MQTT_DEVICE_JSON_STATE		TOPIC_BASE_JSON_STATE												
#define TOPIC_BASE_MQTT_DEVICE_COMMAND			TOPIC_BASE_COMMAND
#define TOPIC_BASE_MQTT_DEVICE_STATE			TOPIC_BASE_STATE